name: HotBarSwapper
version: '${project.version}'
main: tech.michaelparker.hotbarswapper.HotBarSwapper
api-version: 1.20
commands:
  startSwapping:
    description: Start swapping hotbars
    usage: /<command>¬