name: HotBarSwapper
version: '1.0.0' # Replace this with the actual version of your plugin
main: tech.michaelparker.hotbarswapper.HotBarSwapper
api-version: 1.20
commands:
  startswap:
    description: Start the hotbar swapping process for all players online.
    usage: /<command>
